#./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:
  run:
    aliases: [r]
    desc: "Start the application"
    cmds:
      - go run ./cmd/sso/main.go --config=./config/local.yaml
  migrate:
    aliases: [mig]
    desc: "Run migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
